### PR TITLE
Switches transform message to json to support sending blank data_dir.

### LINKED ISSUE #468: Dev: trying to run all transforms leads to error:
Steps to reproduce

* Go into dev -> Site administration -> Transform data
* Leave path field blank
* Click "Begin transform"
* Receive "We're sorry, but something went wrong."

Seems to trigger the following: https://app.honeybadger.io/projects/53082/faults/46255424 (see #432)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #468

### CODE REVIEW

File: app/services/transform_notification.rb [hunk 1]
```diff
@@ -18,4 +18,8 @@ def publish(data_dir)
   def client
     Aws::SNS::Client.new
   end
+
+  def message(data_dir)
+    JSON.generate(data_dir: data_dir || nil)
```
Comment (jcoyne) [inline app/services/transform_notification.rb]: I'm not sure I understand what the `data_dir || nil` would accomplish.  is this casting `false` to `nil`?  Do we need to consider the case of an empty string?

Comment (justinlittman) [reply app/services/transform_notification.rb]: It does nothing in Ruby. But it works great in Python.

The lambda will handle it being either null or blank.
